### ISSUE TITLE
Add TF serving 1.15 support

### ISSUE THREAD

**Issue by gogasca** [bitnami/bitnami-docker-tensorflow-serving#12]
https://github.com/tensorflow/serving/releases/tag/1.15.0

**Comment by carrodher** [comment]
Hi, thanks for the suggestion.

When the `2.X` branch was released upstream, we replaced the `1.X` branch by the new one. 
It seems the `1.X` branch is still alive so I just created an internal task to continue supporting both branches following the same deprecation timing as upstream.

**Comment by fmulero** [comment]
TF 1 is out of support right now.

We are also moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still interested on this feature, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
