### ISSUE TITLE
can provide gpu support?

### ISSUE THREAD

**Issue by qujinqiang** [bitnami/bitnami-docker-tensorflow-serving#5]
as the title, i want a gpu support version
thanks

**Comment by javsalgar** [comment]
This is not trivial because, as far as I know, that would imply compiling tensorflow with the nvidia toolkit. Then, you would have to mount your own drivers and libraries to make it work (we cannot redistribute the NVIDIA libraries in the image). We created a blog post for our cloud images: https://docs.bitnami.com/google/how-to/enable-nvidia-gpu-tensorflow-serving/

In any case, let's leave this ticket open for future evaluation of including the feature :)

**Comment by adgelbfish** [comment]
can't this be done with https://github.com/NVIDIA/nvidia-docker?

**Comment by javsalgar** [comment]
I didn't hear about it, do you know how it would be integrated with tensorflow? Because it looks like we would have to build a container that forks from this one.

**Comment by javsalgar** [comment]
I still have my concerns about the licensing and redistribution of the binaries. Anyways, I forwarded the information and will be evaluated for future releases

**Comment by vinayak19th** [comment]
Any updates regarding GPU support?

**Comment by javsalgar** [comment]
I'm afraid we are not allowed to redistribute the nvidia gpu toolkit. You would need to build it yourself by forking the one we have. We have this guide for cloud images: https://docs.bitnami.com/google/how-to/enable-nvidia-gpu-tensorflow-serving/

**Comment by vinayak19th** [comment]
Sure. Thanks for the update.
